language: generic

os: linux
dist: bionic

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - DOCKER_CLI_EXPERIMENTAL=enabled PYTHON_BASE_IMAGE=3.8-slim-buster TAG=python3

before_install:
  - sudo rm -rf /var/lib/apt/lists/*
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker run --rm --privileged  docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64

script:
  - make buildx

before_deploy: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - script: make buildx-push
    if: branch = master AND type IN (push)

