sudo: required

env:
  global:
    - TAG: automatic

services:
  - docker

script:
  - if [[ $TAG == "master" ]]; then DOCKER_TAG="latest"; else DOCKER_TAG="$TAG"; fi
  - echo "Building octroprint branch/tag $TAG into gaetancollaud/octoprint:$DOCKER_TAG"
  - if [[ "$TAG" != "automatic" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - docker build --build-arg tag=$TAG -t gaetancollaud/octoprint:$DOCKER_TAG .
  - if [[ "$TAG" != "automatic" ]]; then docker push gaetancollaud/octoprint:$DOCKER_TAG; fi
