sudo: required

language: python

dist: bionic

addons:
  apt:
    update: true
    packages: jq

services:
  - docker

stages:
  - build
  - deploy

jobs:
  include:
    - stage: build
      script: make build
    - stage: deploy
      script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      script: make release 
      on:
        branch: master
