language: generic

os: linux
dist: bionic

install: './.travis/install.sh'

services:
  - docker

stages:
  - validate
  - build

jobs:
  include:
    - stage: validate
      script: make validate
    - stage: build
      script: make build

deploy:
  provider: script
  script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make release
  on:
    branch: master
