sudo: required

env:
  global:
    - TAG: master

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build --build-arg tag=$TAG -t gaetancollaud/octoprint:$TAG .
  - docker push gaetancollaud/octoprint:$TAG
  - if [[ "$TAG" == "master" ]]; then docker tag gaetancollaud/octoprint:$TAG gaetancollaud/octoprint:latest && docker push gaetancollaud/octoprint:latest; fi
