sudo: required

env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.4.2
    - TAG: master
    - IMAGE_NAME: gaetancollaud/octoprint

services:
  - docker

script:
  - docker build --build-arg tag=$TAG -t $IMAGE_NAME:$TAG .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $IMAGE_NAME:$TAG
