sudo: required

env:
  global:
    - TAG=master DOCKER_TAG=1.40-python3

services:
  - docker
arch:
  - amd64
  - arm64
  - arm

script:
  - echo "Building octroprint branch/tag $TAG into octoprint/octoprint:$DOCKER_TAG"
  - docker build --build-arg tag=$TAG -t octoprint/octoprint:$DOCKER_TAG .
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"; fi
  - if [[ "$DOCKER_TAG" != "automatic" ]]; then docker push octoprint/octoprint:$DOCKER_TAG; fi
