version: '3.7'

services:
  octoprint:
    image: octoprint/octoprint
    ports:
      - 80:8888
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    # - /dev/video0:/dev/video0
    volumes:
     - octoprint:/octoprint

volumes:
  octoprint:
