version: '3.7'

services:
  octoprint:
    image: octoprint/octoprint
    ports:
      - 80:80
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
     - octoprint:/octoprint

volumes:
  octoprint:
