name: Build Images

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  filters:
    runs-on: ubuntu-latest
    outputs:
      found_main_changes: ${{ steps.filter.outputs.main_image_files }}
      found_minimal_changes: ${{ steps.filter.outputs.minimal_image_files }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.1
      id: filter
      with:
        filters: '.github/filter.yml'

  build:
    runs-on: ubuntu-latest
    needs: filters
    if: needs.filters.outputs.found_main_changes
    
    steps:
      - uses: actions/checkout@v2
      - name: Get OctoPrint Stable
        id: get-octoprint-release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: OctoPrint
          repo: OctoPrint
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Build Image
        id: build
        run: |
          docker buildx build --push \
            --platform linux/arm64,linux/amd64,linux/arm/v7 \
            --cache-from octoprint/octoprint:cache \
            --cache-to octoprint/octoprint:cache \
            --build-arg tag=${{ steps.get-octoprint-release.outputs.release }} \
            --progress plain -t octoprint/octoprint:ci -f Dockerfile .
