name: Multi-Arch Image Build


on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: v0.3.1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outps.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --output type=image,push=false \
            .
            
