name: Build and Verify Image

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: setup
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Available platforms
        run: |
          echo ${{ steps.setup.outputs.platforms }}
      - name: Run Buildx
        id: buildx
        run: |
          echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME}} --password-stdin
          make buildx
      - name: Cleanup
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
